'use client'

import { Excalidraw, MainMenu, WelcomeScreen } from '@excalidraw/excalidraw'
import { Sparkles, X, PlusSquare } from 'lucide-react'
import { useDrawnixBoard } from './useDrawnixBoard'
import '@excalidraw/excalidraw/index.css'

interface DrawnixBoardProps { id: string; initialData: any; readonly?: boolean }

export default function DrawnixBoard({ id, initialData, readonly = false }: DrawnixBoardProps) {
  const board = useDrawnixBoard({ id, initialData, readonly })
  return <div className="h-full flex flex-col relative">
    {!readonly && <div className="p-2 border-b flex justify-between items-center bg-gray-50"><div className="flex items-center gap-2"><span className="text-sm text-gray-500">专业白板 (Excalidraw)</span>{board.isSaving && <span className="text-xs text-gray-400">保存中...</span>}</div><div className="flex items-center gap-2"><button onClick={board.handleAddLibraryItem} className="flex items-center gap-1 px-3 py-1 text-gray-600 hover:bg-gray-100 rounded text-sm transition-colors" title="选中画布上的元素，点击此按钮将其注册为带名称的素材"><PlusSquare size={14} />注册素材</button><button onClick={() => board.setShowAIDialog(true)} className="flex items-center gap-1 px-3 py-1 bg-purple-600 text-white rounded hover:bg-purple-700 text-sm transition-colors"><Sparkles size={14} />AI 生成图表</button><button onClick={board.handleSave} disabled={board.isSaving} className="px-3 py-1 bg-blue-600 text-white rounded hover:bg-blue-700 text-sm disabled:opacity-50">{board.isSaving ? '保存中...' : '保存'}</button></div></div>}
    <div className="flex-1 w-full h-full overflow-hidden bg-white relative"><Excalidraw initialData={board.initData} excalidrawAPI={(api) => board.setExcalidrawAPI(api)} langCode="zh-CN" viewModeEnabled={readonly} onLibraryChange={(items) => board.setLibraryItems(Array.from(items))} UIOptions={{ canvasActions: { saveToActiveFile: false, loadScene: false, export: { saveFileToDisk: !readonly }, saveAsImage: !readonly } }}><MainMenu><MainMenu.DefaultItems.Export /><MainMenu.DefaultItems.SaveAsImage /><MainMenu.DefaultItems.ClearCanvas /><MainMenu.DefaultItems.ChangeCanvasBackground /><MainMenu.DefaultItems.Help /></MainMenu><WelcomeScreen /></Excalidraw></div>
    {board.showAIDialog && <div className="absolute inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"><div className="bg-white rounded-lg shadow-xl w-[400px] p-4 animate-in fade-in zoom-in duration-200"><div className="flex items-center justify-between mb-4"><h3 className="font-medium flex items-center gap-2"><Sparkles className="text-purple-600" size={18} />AI 图表生成</h3><button onClick={() => board.setShowAIDialog(false)} className="text-gray-400 hover:text-gray-600"><X size={18} /></button></div><div className="space-y-4"><div><label className="block text-xs text-gray-500 mb-1">描述你想要的图表</label><textarea value={board.aiPrompt} onChange={(event) => board.setAiPrompt(event.target.value)} placeholder="例如：画一个用户登录注册的流程图，包含忘记密码的分支..." className="w-full h-32 p-3 text-sm border rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 resize-none" /><div className="text-xs text-gray-400 mt-1 flex flex-col gap-1"><div className="flex justify-between items-center w-full"><span>支持 Mermaid 语法描述</span>{board.libraryItems.length > 0 && <span className="text-purple-600 font-medium">已加载 {board.libraryItems.length} 个素材</span>}</div>{board.libraryItems.length > 0 && <div className="flex flex-col gap-1 w-full"><div className="text-[10px] text-gray-500 truncate">可用: {board.libraryItems.filter((item: any) => item.name?.trim()).map((item: any) => item.name).join(', ') || '无'}</div>{board.libraryItems.some((item: any) => !item.name?.trim()) && <div className="text-[10px] text-amber-600 bg-amber-50 p-1 rounded border border-amber-100">⚠️ 检测到 {board.libraryItems.filter((item: any) => !item.name?.trim()).length} 个未命名素材。<br />请在右侧素材库中切换到列表视图并重命名，否则 AI 无法使用。</div>}</div>}</div></div><div className="flex justify-end gap-2"><button onClick={() => board.setShowAIDialog(false)} className="px-3 py-1.5 text-sm text-gray-600 hover:bg-gray-100 rounded">取消</button><button onClick={board.handleAIGenerate} disabled={board.isGenerating || !board.aiPrompt.trim()} className="flex items-center gap-2 px-4 py-1.5 text-sm bg-purple-600 text-white rounded hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed">{board.isGenerating ? <><span className="animate-spin">⏳</span>生成中...</> : <><Sparkles size={14} />开始生成</>}</button></div></div></div></div>}
  </div>
}
