'use client'

import dynamic from 'next/dynamic'
import { ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import TiptapToolbar from '@/components/editor/TiptapToolbar'
import { useNewNotePage } from './useNewNotePage'

const MarkdownEditor = dynamic(() => import('@/components/editor/MarkdownEditor'), { ssr: false, loading: () => <div className="animate-pulse bg-gray-100 h-[500px] rounded" /> })
const TiptapEditor = dynamic(() => import('@/components/editor/TiptapEditor'), { ssr: false })

export default function NewNotePage() {
  const page = useNewNotePage()
  return <div className="space-y-6">
    <div className="flex items-center justify-between"><div className="flex items-center gap-4"><Button variant="ghost" size="icon" onClick={page.handleCancel} className="text-gray-500 hover:text-gray-700"><ArrowLeft className="h-4 w-4" /></Button><h1 className="text-2xl font-bold" style={{ background: 'linear-gradient(to right, #111827, #2563eb, #111827)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>新建笔记</h1></div></div>
    <div className="bg-white" style={{ borderRadius: '12px', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)' }}>
      <div className="grid gap-6 border-b border-gray-100 p-6 md:grid-cols-2">
        <div><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-gray-700">选择分类</span>{page.metaLoading && <span className="text-xs text-gray-400">加载中...</span>}</div><select className="w-full rounded-lg border border-gray-200 p-3 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200" value={page.selectedCategory} onChange={(event) => page.setSelectedCategory(event.target.value)} disabled={page.metaLoading || !!page.metaError}><option value="">未分类</option>{page.categories.map((category) => <option key={page.resolveCategoryId(category) || category.name} value={page.resolveCategoryId(category)}>{category.name}</option>)}</select><div className="mt-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-gray-700">附属分类（仅用于标签）</span></div><div className="max-h-56 overflow-auto rounded-lg border border-gray-200 p-3">{(page.childrenByParent.__root__ || []).map((category) => <CategoryTreeNode key={page.resolveCategoryId(category) || category.name} category={category} level={0} childrenByParent={page.childrenByParent} selectedIds={page.auxCategoryIds} expanded={page.expandedCats} onToggleSelected={(id, checked) => page.setAuxCategoryIds((previous) => checked ? Array.from(new Set([...previous, id])) : previous.filter((item) => item !== id))} onToggleExpanded={(id) => page.setExpandedCats((previous) => ({ ...previous, [id]: !previous[id] }))} resolveId={page.resolveCategoryId} />)}</div></div></div>
        <div><div className="mb-4"><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-gray-700">可见性</span></div><select className="w-full rounded-lg border border-gray-200 p-3 text-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200" value={page.visibility} onChange={(event) => page.setVisibility(event.target.value as 'private' | 'org' | 'public')}><option value="private">仅自己</option><option value="org">组织内</option><option value="public">公开只读</option></select></div><div className="mb-2 flex items-center justify-between"><span className="text-sm font-medium text-gray-700">标签（可多选）</span>{page.metaLoading && <span className="text-xs text-gray-400">加载中...</span>}</div><div className="mb-2 flex items-center gap-2"><input type="text" value={page.tagInput} onChange={(event) => page.setTagInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') { const parts = page.tagInput.split(/[,\s]+/); page.setTagInput(''); void page.addTagsByNames(parts) } }} placeholder="输入标签，Enter 添加，支持逗号分隔" className="flex-1 rounded-lg border border-gray-200 p-2 text-sm" /><button className="px-3 py-1 rounded border text-sm text-gray-700 hover:bg-gray-50" onClick={() => page.setSelectedTags([])}>清空标签</button></div>{page.tagInput && <div className="mb-2 rounded-lg border border-gray-200 p-2 bg-white shadow-sm"><div className="text-xs text-gray-500 mb-1">建议</div><div className="flex flex-wrap gap-2">{page.tags.filter((tag) => tag.name.toLowerCase().includes(page.tagInput.toLowerCase())).slice(0, 10).map((tag) => { const id = page.resolveTagId(tag); return <button key={id || tag.name} type="button" onClick={() => id && page.toggleTag(id)} className="rounded-full border px-3 py-1 text-xs hover:border-blue-300 hover:text-blue-600">{tag.name}</button> })}<button type="button" onClick={() => { void page.addTagsByNames([page.tagInput]); page.setTagInput('') }} className="rounded-full border px-3 py-1 text-xs text-gray-700 hover:bg-gray-50">创建标签 “{page.tagInput}”</button></div></div>}{page.tags.length === 0 ? <p className="text-sm text-gray-400">{page.metaError || '暂无可用标签'}</p> : <div className="flex flex-wrap gap-2">{page.tags.map((tag) => { const id = page.resolveTagId(tag); const active = id ? page.selectedTags.includes(id) : false; return <button key={id || tag.name} type="button" onClick={() => id && page.toggleTag(id)} disabled={!id} className={`rounded-full border px-3 py-1 text-sm transition ${active ? 'border-blue-500 bg-blue-50 text-blue-600 shadow-sm' : 'border-gray-200 text-gray-600 hover:border-blue-200 hover:text-blue-500'}`}>{tag.name}</button> })}</div>}</div>
        {page.metaError && <p className="md:col-span-2 text-sm text-red-500">{page.metaError}</p>}
      </div>
      <div className="px-6 pb-2"><div className="flex items-center gap-2"><span className="text-xs text-gray-500">编辑器</span><select className="rounded border px-2 py-1 text-xs" value={page.editorMode} onChange={(event) => page.setEditorMode(event.target.value as 'rich' | 'markdown')}><option value="rich">富文本（协同）</option><option value="markdown">Markdown</option></select></div></div>
      {page.editorMode === 'rich' ? <div ref={page.editorContainerRef} className="space-y-3 p-6" style={page.isFullscreen ? { position: 'fixed', inset: 0, zIndex: 50, width: '100vw', height: '100vh', background: 'transparent' } : undefined}><input type="text" value={page.newTitle} onChange={(event) => page.setNewTitle(event.target.value)} placeholder="标题" className="w-full rounded-lg border border-gray-200 p-3 text-lg focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-200" /><TiptapToolbar disabled={false} isFullscreen={page.isFullscreen} exec={(command, payload) => { if (command === 'comments') return; if (command === 'fullscreen') { page.handleToggleFullscreen(); return } document.dispatchEvent(new CustomEvent('tiptap:exec', { detail: { cmd: command, payload } })) }} /><TiptapEditor noteId="new" initialHTML="<p></p>" onSave={async (html: string) => page.handleSave(page.newTitle, html)} user={{ id: 'me', name: '我' }} readOnly={false} onSelectionChange={(start, end) => page.setSelection({ start, end })} className="min-h-[calc(100vh-200px)]" /></div> : <MarkdownEditor initialContent="" initialTitle="" onSave={page.handleSave} onSaveDraft={page.handleSaveDraft} isNew draftKey="note:new" />}
    </div>
  </div>
}

function CategoryTreeNode({ category, level, childrenByParent, selectedIds, expanded, onToggleSelected, onToggleExpanded, resolveId }: { category: any; level: number; childrenByParent: Record<string, any[]>; selectedIds: string[]; expanded: Record<string, boolean>; onToggleSelected: (id: string, checked: boolean) => void; onToggleExpanded: (id: string) => void; resolveId: (category: any) => string }) {
  const id = resolveId(category)
  const children = childrenByParent[id] || []
  const isExpanded = expanded[id]
  return <div className="py-1"><div className="flex items-center gap-2" style={{ paddingLeft: `${level * 16}px` }}>{children.length > 0 ? <button type="button" onClick={() => onToggleExpanded(id)} className="h-5 w-5 flex items-center justify-center rounded hover:bg-gray-100 text-gray-500" aria-label={isExpanded ? '折叠' : '展开'}>{isExpanded ? '▾' : '▸'}</button> : <span className="h-5 w-5" />}<input type="checkbox" checked={selectedIds.includes(id)} onChange={(event) => onToggleSelected(id, event.target.checked)} className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary" /><span className="text-gray-700 text-sm">{category.name}</span></div>{children.length > 0 && isExpanded && <div>{children.map((child) => <CategoryTreeNode key={resolveId(child) || child.name} category={child} level={level + 1} childrenByParent={childrenByParent} selectedIds={selectedIds} expanded={expanded} onToggleSelected={onToggleSelected} onToggleExpanded={onToggleExpanded} resolveId={resolveId} />)}</div>}</div>
}
